[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "material-database-lab"  # CAMBIA ESTO SI EL NOMBRE YA EXISTE EN PYPI
version = "0.1.0"
authors = [
  { name="Tu Nombre", email="tu@email.com" },
]
description = "Una suite interactiva para simulacion de materiales y ensayos mecanicos"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "streamlit",
    "pandas",
    "plotly",
    "numpy",
    "scipy"
]

[project.scripts]
# Esto crea el comando magico en la terminal
material-lab = "labterial.cli:main"

[project.urls]
"Homepage" = "https://github.com/tu-usuario/tu-repo"
